remote_theme: jekyll/minima

title: "Kero"

include: ['about-cn.md', 'about-en.md']

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/keroro520" }
    - { platform: x,              user_url: "https://x.com/keroroxx520" }
