remote_theme: jekyll/minima

title: "keroro520.github.io"

# author:
#   name: Kero
#   email: "keroroxx520@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/keroro520" }
    - { platform: x,              user_url: "https://x.com/keroroxx520" }

# TOC Settings
toc:
  min_level: 1
  max_level: 3
  list_class: toc
  list_class: toc__list
  sublist_class: toc__sublist
