remote_theme: jekyll/minima

title: "Kero"

include: ['about-cn.md', 'about-en.md']

markdown: kramdown

kramdown:
  math_engine: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/keroro520" }
    - { platform: x,              user_url: "https://x.com/keroroxx520" }
